// INSECURE TEST KEY -- UNSAFE FOR PRODUCTION.
// Generated with `--insecure-test-keys`: the Groth16 setup randomness comes
// from a fixed public seed, so anyone can forge proofs this key accepts. Use
// it only in tests and never deploy a program that verifies against it.
// This file is generated by groth16_solana::vk::gnark.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

static VERIFYINGKEY_VK_IC: &[[u8; 64]] = &[
    [
        2u8, 167u8, 142u8, 226u8, 106u8, 16u8, 153u8, 103u8, 86u8, 246u8, 174u8, 95u8, 193u8,
        240u8, 205u8, 39u8, 28u8, 212u8, 144u8, 238u8, 128u8, 133u8, 204u8, 41u8, 195u8, 200u8,
        189u8, 12u8, 222u8, 136u8, 155u8, 216u8, 26u8, 255u8, 170u8, 182u8, 210u8, 204u8, 252u8,
        131u8, 193u8, 152u8, 68u8, 16u8, 32u8, 198u8, 113u8, 220u8, 26u8, 103u8, 120u8, 148u8,
        57u8, 121u8, 190u8, 132u8, 16u8, 110u8, 31u8, 139u8, 165u8, 188u8, 26u8, 154u8,
    ],
    [
        33u8, 151u8, 10u8, 215u8, 9u8, 191u8, 247u8, 50u8, 245u8, 129u8, 156u8, 178u8, 82u8, 8u8,
        224u8, 144u8, 144u8, 57u8, 251u8, 211u8, 73u8, 0u8, 2u8, 111u8, 177u8, 199u8, 97u8, 18u8,
        36u8, 26u8, 94u8, 52u8, 46u8, 47u8, 93u8, 197u8, 68u8, 35u8, 117u8, 96u8, 233u8, 87u8,
        101u8, 31u8, 7u8, 177u8, 168u8, 102u8, 197u8, 9u8, 15u8, 112u8, 149u8, 83u8, 1u8, 150u8,
        220u8, 181u8, 244u8, 139u8, 28u8, 35u8, 160u8, 192u8,
    ],
];

pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: 1,
    vk_alpha_g1: [
        23u8, 58u8, 38u8, 85u8, 5u8, 97u8, 56u8, 149u8, 234u8, 65u8, 208u8, 250u8, 157u8, 24u8,
        214u8, 220u8, 81u8, 238u8, 128u8, 253u8, 80u8, 84u8, 112u8, 26u8, 115u8, 173u8, 232u8,
        150u8, 69u8, 140u8, 243u8, 66u8, 47u8, 247u8, 169u8, 230u8, 149u8, 167u8, 198u8, 150u8,
        188u8, 45u8, 150u8, 153u8, 26u8, 78u8, 196u8, 31u8, 141u8, 218u8, 188u8, 247u8, 98u8,
        138u8, 75u8, 233u8, 58u8, 58u8, 192u8, 171u8, 90u8, 29u8, 56u8, 236u8,
    ],
    vk_beta_g2: [
        6u8, 113u8, 102u8, 167u8, 235u8, 63u8, 48u8, 3u8, 241u8, 135u8, 184u8, 166u8, 175u8, 133u8,
        228u8, 186u8, 222u8, 158u8, 7u8, 214u8, 151u8, 62u8, 40u8, 214u8, 108u8, 191u8, 218u8,
        121u8, 131u8, 22u8, 35u8, 246u8, 35u8, 254u8, 90u8, 184u8, 0u8, 97u8, 53u8, 224u8, 252u8,
        100u8, 253u8, 142u8, 158u8, 98u8, 89u8, 190u8, 111u8, 118u8, 164u8, 205u8, 73u8, 84u8,
        34u8, 135u8, 35u8, 68u8, 178u8, 235u8, 135u8, 158u8, 93u8, 162u8, 10u8, 182u8, 236u8, 11u8,
        113u8, 54u8, 88u8, 98u8, 199u8, 150u8, 17u8, 243u8, 42u8, 45u8, 214u8, 165u8, 238u8, 242u8,
        134u8, 77u8, 227u8, 150u8, 217u8, 255u8, 138u8, 82u8, 78u8, 72u8, 198u8, 9u8, 148u8, 112u8,
        24u8, 51u8, 119u8, 156u8, 66u8, 88u8, 231u8, 204u8, 215u8, 137u8, 126u8, 37u8, 175u8,
        136u8, 57u8, 54u8, 59u8, 221u8, 0u8, 139u8, 42u8, 135u8, 148u8, 218u8, 63u8, 115u8, 18u8,
        95u8, 217u8, 184u8, 35u8, 135u8,
    ],
    vk_gamma_g2: [
        4u8, 82u8, 14u8, 189u8, 59u8, 221u8, 124u8, 110u8, 223u8, 163u8, 29u8, 204u8, 86u8, 8u8,
        215u8, 79u8, 213u8, 220u8, 109u8, 156u8, 78u8, 180u8, 236u8, 44u8, 144u8, 13u8, 183u8,
        199u8, 161u8, 65u8, 35u8, 79u8, 16u8, 65u8, 196u8, 125u8, 85u8, 153u8, 218u8, 123u8, 134u8,
        91u8, 240u8, 199u8, 27u8, 29u8, 41u8, 37u8, 176u8, 229u8, 55u8, 75u8, 47u8, 115u8, 143u8,
        224u8, 135u8, 90u8, 163u8, 248u8, 253u8, 3u8, 242u8, 42u8, 27u8, 192u8, 153u8, 216u8, 97u8,
        239u8, 20u8, 190u8, 51u8, 108u8, 60u8, 0u8, 63u8, 162u8, 163u8, 57u8, 165u8, 69u8, 115u8,
        228u8, 155u8, 241u8, 161u8, 226u8, 0u8, 28u8, 138u8, 142u8, 80u8, 53u8, 80u8, 173u8, 41u8,
        142u8, 125u8, 227u8, 162u8, 188u8, 62u8, 194u8, 111u8, 175u8, 57u8, 21u8, 169u8, 25u8,
        178u8, 134u8, 66u8, 91u8, 40u8, 222u8, 97u8, 123u8, 153u8, 130u8, 124u8, 88u8, 156u8, 33u8,
        108u8, 217u8, 4u8, 234u8,
    ],
    vk_delta_g2: [
        2u8, 149u8, 148u8, 197u8, 131u8, 60u8, 129u8, 248u8, 196u8, 206u8, 104u8, 21u8, 30u8,
        107u8, 132u8, 130u8, 31u8, 21u8, 182u8, 71u8, 229u8, 253u8, 58u8, 111u8, 223u8, 132u8,
        178u8, 164u8, 39u8, 131u8, 92u8, 7u8, 2u8, 135u8, 47u8, 218u8, 111u8, 208u8, 62u8, 126u8,
        245u8, 255u8, 197u8, 100u8, 64u8, 103u8, 238u8, 76u8, 140u8, 28u8, 36u8, 218u8, 91u8, 38u8,
        254u8, 70u8, 12u8, 176u8, 31u8, 74u8, 244u8, 21u8, 29u8, 155u8, 31u8, 86u8, 232u8, 255u8,
        187u8, 159u8, 17u8, 157u8, 40u8, 221u8, 61u8, 142u8, 182u8, 27u8, 45u8, 248u8, 179u8,
        146u8, 206u8, 34u8, 32u8, 6u8, 140u8, 83u8, 214u8, 251u8, 108u8, 12u8, 6u8, 91u8, 233u8,
        64u8, 34u8, 57u8, 68u8, 11u8, 202u8, 154u8, 30u8, 11u8, 42u8, 120u8, 224u8, 58u8, 245u8,
        81u8, 76u8, 108u8, 131u8, 122u8, 22u8, 75u8, 205u8, 154u8, 79u8, 14u8, 157u8, 205u8, 214u8,
        25u8, 235u8, 68u8, 142u8, 187u8,
    ],
    vk_ic: VERIFYINGKEY_VK_IC,
    vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [216u8, 153u8, 66u8, 116u8, 191u8, 14u8, 36u8, 21u8, 185u8, 156u8, 194u8, 182u8, 252u8, 103u8, 163u8, 138u8, 201u8, 203u8, 79u8, 184u8, 158u8, 179u8, 80u8, 135u8, 233u8, 178u8, 119u8, 232u8, 129u8, 172u8, 96u8, 246u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_d630518fd4f89f88")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x00d8994274bf0e2415b99cc2b6fc67a38ac9cb4fb89eb35087e9b277e881ac60f6\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
