[package]
name = "timelock-escrow-prover"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "timelock_escrow_prover"
path = "src/lib.rs"

[[bin]]
name = "timelock-escrow-prover-setup"
path = "src/bin/setup.rs"

[dependencies]
zolana-gnark-ffi-prover = { workspace = true }
timelock-escrow-program = { path = "../program" }
zolana-client = { workspace = true }

[build-dependencies]
zolana-gnark-ffi-prover-build = { workspace = true }
