[package]
name = "dynamic-swap-program"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "dynamic_swap_program"
crate-type = ["cdylib", "lib"]

[features]
default = []
bpf-entrypoint = []
no-entrypoint = []
cpi = ["no-entrypoint"]
test-sbf = []
profile-program = ["light-program-profiler/profile-program"]

[dependencies]
borsh = { workspace = true }
groth16-solana = { workspace = true, features = ["bsb22"] }
light-program-profiler = { workspace = true }
pinocchio = { workspace = true, features = ["cpi"] }
pinocchio-system = { workspace = true }
solana-program-error = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }
zolana-account-checks = { workspace = true }
zolana-hasher = { workspace = true }
zolana-interface = { workspace = true, features = ["solana"] }
bytemuck = { workspace = true }

[lints.rust.unexpected_cfgs]
level = "allow"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]
