allowBuilds:
  "@heliuslabs/zolana@https://codeload.github.com/helius-labs/zolana/tar.gz/a3ddedda42b40d4951ae8fcdde2500374c4f2125#path:/sdk-libs/ts": true
  esbuild: true
minimumReleaseAgeExclude:
  - "@heliuslabs/zolana"
