allowBuilds:
  "@heliuslabs/zolana@https://codeload.github.com/helius-labs/zolana/tar.gz/0fde5f1e1e209b85896362c9293ec0b60bbf7563#path:/sdk-libs/ts": true
  esbuild: true
minimumReleaseAgeExclude:
  - "@heliuslabs/zolana"
