allowBuilds:
  "@heliuslabs/zolana@https://codeload.github.com/helius-labs/zolana/tar.gz/4c596049e5d17e0f71d94a42573575f14cb0b9dd#path:/sdk-libs/ts": true
  esbuild: true
minimumReleaseAgeExclude:
  - "@heliuslabs/zolana"
