[package]
name = "k-lend-market-maker"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
k-lend-rfq-sdk = { path = "../sdk" }
solana-address = { workspace = true }
solana-commitment-config = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-instruction-error = { workspace = true }
solana-message = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-error = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
zolana-client = { workspace = true, features = ["indexer-api", "solana-rpc"] }
zolana-interface = { workspace = true }
zolana-keypair = { workspace = true }
zolana-program = { workspace = true }
zolana-transaction = { workspace = true }

[dev-dependencies]
k-lend-rfq-test-utils = { path = "../test-utils" }
zolana-program-test = { workspace = true, features = ["localnet"] }
zolana-test-utils = { workspace = true }
